// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"database/sql"
)

type Blog struct {
	ID        uint64
	Title     string
	Content   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	User      sql.NullInt32
}

type User struct {
	ID       uint64
	Email    string
	Password string
	Name     string
}
